name: Status Check Function
on: [push, workflow_dispatch]

jobs: 
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 20
      - name: Step 2
        id: step-2
        run: exit 1
      - name: Runs on step 2 Failure
        if: failure() && steps.conclusion = 'failure'
        run: echo 'Step 2 has faailed'
      - name: Runs on failure
        if: failure()
        run: echo 'Failure'
      - name: Runs on Success
        if: success()
        run: echo 'Runs on Success'
        
